# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TSPRouteGenerator
                                 A QGIS plugin
 Generates an optimized TSP route within a boundary layer.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-06-23
        copyright            : (C) 2025 by Zach
        email                : zkomarnisky@oldscollege.ca
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TSPRouteGenerator class from file TSPRouteGenerator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .tsp_route_generator import TSPRouteGenerator
    return TSPRouteGenerator(iface)
